name: Activity Summary

on:
  schedule:
    - cron: '30 7 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r github-notify-ml/requirements.txt
    - name: create instance
      run: |
        mkdir github-notify-ml/instance
        cp config.json mls.json github-notify-ml/instance/
    - name: run github-notify-ml
      env:
        GH_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SMTP_HOST: smtp.fastmail.com
        SMTP_USERNAME: mnot@mnot.net
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_SSL: TRUE
      run: |
        cd github-notify-ml
        python index.py Sunday
      
